apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: sharedpod
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: notebooks-pv-claim-polus-notebooks