apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: swazonic/polus-notebooks-hub-backend:latest
      ports:
        - containerPort: 8002
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/sandbox/"
          name: task-pv-storage
