apiVersion: apps/v1
kind: Deployment
metadata:
  name: polus-notebooks-hub-frontend-deployment
spec:
  selector:
    matchLabels:
      app: polus-notebooks-hub-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: polus-notebooks-hub-frontend
    spec:
      containers:
        - name: polus-notebooks-hub-frontend
          image: swazonic/polus-notebooks-hub-frontend:latest
          ports:
            - containerPort: 4200