apiVersion: v1
kind: Service
metadata:
  name: polus-notebooks-hub-backend-service
spec:
  selector:
    app: polus-notebooks-hub-backend
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 31000